---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
  - name: state
  - name: 1-click
outputs:
  - name: out-state

params:
  BOSH_LITE_NAME: unconfigured
  DOMAIN_NAME: unconfigured
  MANIFEST: unconfigured

run:
  path: 1-click/tasks/bosh-create-env.sh

caches:
- path: .bosh/cache
- path: .bosh/downloads
- path: .bosh/installations
- path: .bosh/tmp
