---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
  - name: bosh-deployment
  - name: 1-click
  - name: state

outputs:
  - name: out-state

params:
  BOSH_LITE_NAME: unconfigured

run:
  path: 1-click/tasks/update-runtime-config.sh
